<?php
$title = 'Add new Event';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>

<?php
$form = $this->form;
$form->setAttribute('action', $this->url('event', array(
    'action' => 'add'
)));
$form->get('submit')->setAttribute('value', 'Add');
$form->prepare();

echo $this->form()->openTag($form);
echo $this->formHidden($form->get('id'));
echo $this->formRow($form->get('name'));
echo $this->formRow($form->get('plz'));
echo $this->formRow($form->get('ort'));
echo $this->formRow($form->get('strasse'));
echo $this->formRow($form->get('hausnummer'));
echo $this->formRow($form->get('vorid'));
echo $this->formRow($form->get('preis'));
echo $this->formRow($form->get('datum'));
echo $this->formRow($form->get('geschlecht'));
echo $this->formRow($form->get('beschreibung'));
// echo $this->formRow($form->get('jahrgang'));
?>
<div>
 <?php echo $this->formInput($form->get('submit')); ?>
 </div>
<?php
echo $this->form()->closeTag($form);
?>
<p>
	<a
		href="<?php

echo $this->url('event', array(
    'action' => 'index'
));
?>">Uebersicht</a>
</p>