<?php
use Zend\Filter\DateTimeFormatter;
$title = 'My Veranstaltung list';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<p>
	<a
		href="<?php

// echo $this->url('event', array(
//     'action' => 'add'
// ));
?>">Add new item</a>
</p>

<table class="table">
	<tr>
		<th>Name:</th>
	</tr>
 <?php foreach ($veranstaltungen as $veranstaltung): ?>
 <tr>
		<td><a
			href="<?php
    
echo $this->url('veranstaltung', array(
        'action' => 'show',
        'id' => $veranstaltung->getId()
    ));
    ?>">
             <?php echo $this->escapeHtml($veranstaltung->getName()); ?></a></td>
			
 <?php endforeach; ?>
 </table>