<?php
use Zend\Filter\DateTimeFormatter;
$title = 'My event list';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<table class="table">
<tr>
<th>Name</th>
<th>Ort</th>
<th>PLZ</th>
<th>Strasse</th>
<th>Hausnummer</th>
<th>Datum</th>
<th>Meisterschaft</th>
<th>Geschlecht</th>
<th>Gebuehr</th>
<th>&nbsp;</th>
</tr>
 <?php foreach ($events as $event): ?>
 <tr>
		<td><a
			href="<?php
    
echo $this->url('event', array(
        'action' => 'edit',
        'id' => $event->getId()
    ));
    ?>">
             <?php echo $this->escapeHtml($event->getName()); ?></a></td>
		<td><?php echo $this->escapeHtml($event->getOrt()); ?></td>
		<td><?php echo $this->escapeHtml($event->getPlz()); ?></td>
		<td><?php echo $this->escapeHtml($event->getStrasse()); ?></td>
		<td><?php echo $this->escapeHtml($event->getHausnummer()); ?></td>
		<td><?php echo $this->escapeHtml(DateTime::createFromFormat('Y-m-d H:i:s', $event->getDatum())->format('Y-m-d H:i')); ?></td>
		<td><?php echo $event->getMeisterschaft() ? $event->getMeisterschaft() : 'No'; ?></td>
		<td><?php echo $event->getGeschlecht() != 'N' ? $event->getGeschlecht() : 'No'; ?></td>
		<td><?php echo $this->escapeHtml($event->getPreis()); ?> &#8364;</td>
			
 <?php endforeach; ?>
 </table>